config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/WORSICA/eosc-worsica-intermediate:
      branch: main
      repo: https://github.com/WORSICA/eosc-worsica-intermediate
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/WORSICA/eosc-worsica-intermediate git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-asparagus-macaw.sh
        container: qc.acc_snippy-firebrick-fousek
  QC.Doc:
    repos:
      github.com/WORSICA/eosc-worsica-intermediate find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-wheat-bobcat.sh
        container: qc.doc_gimpy-harlequin-wallaby
      github.com/WORSICA/eosc-worsica-intermediate git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-fuchsia-newt.sh
        container: qc.doc_snappy-cyan-forest
      github.com/WORSICA/eosc-worsica-intermediate markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-puce-forest.sh
        container: qc.doc_tacky-cerise-kakapo
  QC.Lic:
    repos:
      github.com/WORSICA/eosc-worsica-intermediate licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-dandelion-wolf.sh
        container: qc.lic_muzzy-grey-zebra
  QC.Met:
    repos:
      github.com/WORSICA/eosc-worsica-intermediate cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-emerald-whippet.sh
        container: qc.met_stuffy-fuchsia-indri
      github.com/WORSICA/eosc-worsica-intermediate validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-brass-capuchin.sh
        container: qc.met_squirrely-goldenrod-discus
  QC.Sec:
    repos:
      github.com/WORSICA/eosc-worsica-intermediate bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-lilac-wolverine.sh
        container: qc.sec_gimpy-cerise-yak
  QC.Sty:
    repos:
      github.com/WORSICA/eosc-worsica-intermediate flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-khaki-numbat.sh
        container: qc.sty_trippy-bronze-fish
      github.com/WORSICA/eosc-worsica-intermediate jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-cinnamon-macaque.sh
        container: qc.sty_hazy-corn-mongrel
  QC.Ver:
    repos:
      github.com/WORSICA/eosc-worsica-intermediate get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-tan-sponge.sh
        container: qc.ver_hilly-black-shark
timeout: 5400
